[package]
name = "fakenotify-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bincode.workspace = true
bitflags.workspace = true
libc.workspace = true
serde.workspace = true
thiserror.workspace = true
